### PR TITLE
Adding custom_class support to select how a list of repositories are returned

### PR DESCRIPTION
**Pull request by halkeye**
Gives the ability to create custom modules for workplaces

IE:
Model::CollectionOfRepos
    custom_class Gitalist::Git::CollectionOfRepositories::FromDirectory::Gitolite
    repo_dir /home/git/repositories/
/Model::CollectionOfRepos

(i'm going to submit a pull request for Gitalist::Git::CollectionOfRepositories::FromDirectory::Gitolite or a seperate module after a lot more testing)

### CODE REVIEW

**Comment by broquaint** [comment]
Thanks for that, @halkeye. Interestingly the functionality of defining a custom model has recently landed in master (but hasn't made it to the CPAN yet) - https://github.com/broquaint/Gitalist/blob/master/lib/Gitalist/Model/CollectionOfRepos.pm#L18 Great minds think alike and all that :) However the current functionality only allows for a static set of arguments\* whereas your patch exposes the remote_user to all Model objects that are built, which to my mind isn't ideal. I'll have a think on how we might be able to meet halfway on this as having a Gitolite based model would be really neat.

Cheers,
broquaint
- https://github.com/broquaint/Gitalist/blob/master/README#L184

**Comment by halkeye** [comment]
For the custom_class bit I can easily use class instead, I didn't notice that.

Any ideas on how to handle remote_user yet? I'd like to release my module but it depends on that (or hacking and just using $ENV{REMOTE_USER} and I don't know how portable that is)

**Comment by broquaint** [comment]
Having thought about this it seems best just to have `$ctx->request->remote_user` passed in for now and we can worry about abstraction goodness later. So if you could make another pull request with just the `remote_user` addition in `build_per_context_instance` I'll be happy to merge it :)

**Comment by broquaint** [comment]
Actually, scratch that, after some discussion with @bobtfish we'll just pass the whole request into the class constructor. It's the path we're heading down anyway and at this distance seems to be the cleaner approach anyway. I'll patch that in and push it up. Hopefully we'll be able to push out a release in the not too distant future i.e the next week or two.

**Comment by halkeye** [comment]
any word on when the next release will be?

**Comment by broquaint** [comment]
Thanks for the reminder, I've got one nasty bug cornered and the others on the ropes. If I don't have a release out by the end of the week then you have my word as a gentleman that IOU a beer.

**Comment by broquaint** [comment]
I've just pushed out another release, 0.003008, which introduces a bit of ugliness but should make extensible request-informed CollectionOfRepositories classes possible (it seems to work for the Vhost COR at least). To get access to the request object your COR class will need to implement an ACCEPT_CONTEXT method which should produce another COR (either itself or a delegate). That's the concession we're making to keep the simple stuff simple and the more advanced stuff possible.

This is the commit that introduces much of the changes:

https://github.com/broquaint/Gitalist/commit/4d334b5359bb28a7b0781c44db9ebe710be22965

If none of that makes sense feel free to send me a message ;)

**Pull request closed without merging**
