### PR TITLE
Massive tree action speedup

### PR DESCRIPTION
**Pull request by seveas**
The tree action used to use $tree_obj->tree to get all tree entries.
This is ridiculously slow as it loads all blobs via git cat-file.
Instead, expose directory_entries from the underlying Git::PurePerl
object and use it instead.

This also required moving _mode_str (now mode_string for consistency) to
Gitalist::Utils so it could be used in the template.

### CODE REVIEW

**Comment by broquaint** [comment]
Thanks for this @seveas but it looks to break the interface behind the AJAX requests in the tree view that provide the last commit for a given file/directory. It wasn't obvious at a quick glance where the breakage lies.

**Comment by seveas** [comment]
Strange, that isn't broken for me, the commit info is still loaded.

**Comment by seveas** [comment]
Example of something I see in the debug log:

[info] **\* Request 47 (1.119/s) [29081] [Fri Sep 28 13:38:52 2012] ***
[debug] Path is "/fragment/ref/file_commit_info"
[debug] Arguments are "test.pl"
[debug] "GET" request for "fragment/Gitalist/f1dceb904c530c9ad608f5c9ef26a7e5f855dc09/file_commit_info/test.pl" from "127.0.0.1"
[debug] Response Code: 200; Content-Type: application/json; Content-Length: 110
[info] Request took 0.172995s (5.781/s)

What do you get instead?

**Comment by broquaint** [comment]
Sorry it took so long and thanks for the hard work!

**Pull request merged**
